// Generated by gencpp from file f1tenth_simulator/pid_input.msg
// DO NOT EDIT!


#ifndef F1TENTH_SIMULATOR_MESSAGE_PID_INPUT_H
#define F1TENTH_SIMULATOR_MESSAGE_PID_INPUT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace f1tenth_simulator
{
template <class ContainerAllocator>
struct pid_input_
{
  typedef pid_input_<ContainerAllocator> Type;

  pid_input_()
    : pid_vel(0.0)
    , pid_error(0.0)  {
    }
  pid_input_(const ContainerAllocator& _alloc)
    : pid_vel(0.0)
    , pid_error(0.0)  {
  (void)_alloc;
    }



   typedef float _pid_vel_type;
  _pid_vel_type pid_vel;

   typedef float _pid_error_type;
  _pid_error_type pid_error;





  typedef boost::shared_ptr< ::f1tenth_simulator::pid_input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f1tenth_simulator::pid_input_<ContainerAllocator> const> ConstPtr;

}; // struct pid_input_

typedef ::f1tenth_simulator::pid_input_<std::allocator<void> > pid_input;

typedef boost::shared_ptr< ::f1tenth_simulator::pid_input > pid_inputPtr;
typedef boost::shared_ptr< ::f1tenth_simulator::pid_input const> pid_inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f1tenth_simulator::pid_input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f1tenth_simulator::pid_input_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::f1tenth_simulator::pid_input_<ContainerAllocator1> & lhs, const ::f1tenth_simulator::pid_input_<ContainerAllocator2> & rhs)
{
  return lhs.pid_vel == rhs.pid_vel &&
    lhs.pid_error == rhs.pid_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::f1tenth_simulator::pid_input_<ContainerAllocator1> & lhs, const ::f1tenth_simulator::pid_input_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace f1tenth_simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::f1tenth_simulator::pid_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f1tenth_simulator::pid_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f1tenth_simulator::pid_input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f1tenth_simulator::pid_input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f1tenth_simulator::pid_input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f1tenth_simulator::pid_input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f1tenth_simulator::pid_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15d51ace2dba29e1b19e1332c9d46c17";
  }

  static const char* value(const ::f1tenth_simulator::pid_input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15d51ace2dba29e1ULL;
  static const uint64_t static_value2 = 0xb19e1332c9d46c17ULL;
};

template<class ContainerAllocator>
struct DataType< ::f1tenth_simulator::pid_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1tenth_simulator/pid_input";
  }

  static const char* value(const ::f1tenth_simulator::pid_input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f1tenth_simulator::pid_input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pid_vel\n"
"float32 pid_error\n"
;
  }

  static const char* value(const ::f1tenth_simulator::pid_input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f1tenth_simulator::pid_input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pid_vel);
      stream.next(m.pid_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f1tenth_simulator::pid_input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f1tenth_simulator::pid_input_<ContainerAllocator>& v)
  {
    s << indent << "pid_vel: ";
    Printer<float>::stream(s, indent + "  ", v.pid_vel);
    s << indent << "pid_error: ";
    Printer<float>::stream(s, indent + "  ", v.pid_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // F1TENTH_SIMULATOR_MESSAGE_PID_INPUT_H
